name: 'Setup Node.js'
description: 'Setup Node.js and install dependencies'
inputs:
  working-directory:
    description: 'Working directory'
    required: false
    default: 'frontend'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -f "package-lock.json" ]; then
          npm ci --legacy-peer-deps
        else
          npm install --legacy-peer-deps
        fi
