name: Infrastructure CI/CD Pipeline

on:
  push:
    branches: [main, dev, staging]
    paths: ['terraform/**']
  pull_request:
    branches: [main, dev, staging]
    paths: ['terraform/**']
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options: [dev, staging, prod]
      action:
        description: 'Action to perform'
        required: true
        default: 'plan'
        type: choice
        options: [plan, apply, destroy]

env:
  TF_VERSION: '1.6.0'
  AWS_REGION: eu-west-1

jobs:
  terraform-validate:
    runs-on: [self-hosted, frontend]
    strategy:
      matrix:
        environment: ${{ github.ref == 'refs/heads/dev' && fromJSON('["dev"]') || github.ref == 'refs/heads/staging' && fromJSON('["staging"]') || github.ref == 'refs/heads/main' && fromJSON('["prod"]') || github.event_name == 'workflow_dispatch' && fromJSON(format('[{0}]', toJSON(inputs.environment))) || fromJSON('["dev", "staging", "prod"]') }}
    
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip curl wget
        
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Format Check
      run: terraform fmt -check -recursive terraform/

    - name: Terraform Init (modules)
      run: |
        for module in terraform/modules/*/; do
          if [ -d "$module" ]; then
            module_name=$(basename "$module")
            # Skip ACM module as it requires provider aliases
            if [ "$module_name" = "acm" ]; then
              echo "Skipping $module_name (requires provider aliases)..."
              continue
            fi
            echo "Validating $module_name..."
            cd "$module"
            terraform init -backend=false
            terraform validate
            cd - > /dev/null
          fi
        done

    - name: Terraform Init (environment)
      run: |
        cd terraform/environments/${{ matrix.environment }}
        terraform init -backend=false

    - name: Terraform Validate
      run: |
        cd terraform/environments/${{ matrix.environment }}
        terraform validate

    - name: TFLint Setup
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: latest

    - name: Run TFLint
      run: |
        cd terraform/environments/${{ matrix.environment }}
        tflint --init
        tflint

  terraform-security-scan:
    runs-on: [self-hosted, frontend]
    needs: terraform-validate
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: terraform/
        framework: terraform
        output_format: sarif
        output_file_path: checkov-report.sarif
        soft_fail: true

    - name: Upload Checkov scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: checkov-report.sarif

    - name: Run TFSec
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        working_directory: terraform/
        format: sarif
        soft_fail: true

  terraform-plan:
    runs-on: [self-hosted, frontend]
    needs: [terraform-validate, terraform-security-scan]
    if: github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && inputs.action == 'plan')
    strategy:
      matrix:
        environment: ${{ github.ref == 'refs/heads/dev' && fromJSON('["dev"]') || github.ref == 'refs/heads/staging' && fromJSON('["staging"]') || github.ref == 'refs/heads/main' && fromJSON('["prod"]') || github.event_name == 'workflow_dispatch' && fromJSON(format('[{0}]', toJSON(inputs.environment))) || github.event_name == 'pull_request' && fromJSON('["dev", "staging", "prod"]') || fromJSON('["dev"]') }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: |
        cd terraform/environments/${{ matrix.environment }}
        terraform init

    - name: Terraform Plan
      id: plan
      run: |
        cd terraform/environments/${{ matrix.environment }}
        terraform plan -no-color -out=tfplan
        terraform show -no-color tfplan > plan.txt

    - name: Comment PR with Plan
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const plan = fs.readFileSync('terraform/environments/${{ matrix.environment }}/plan.txt', 'utf8');
          const maxGitHubBodyCharacters = 65536;
          
          function chunkSubstr(str, size) {
            const numChunks = Math.ceil(str.length / size)
            const chunks = new Array(numChunks)
            for (let i = 0, o = 0; i < numChunks; ++i, o += size) {
              chunks[i] = str.substr(o, size)
            }
            return chunks
          }
          
          const planChunks = chunkSubstr(plan, maxGitHubBodyCharacters);
          
          for (let i = 0; i < planChunks.length; i++) {
            const output = `### Terraform Plan (${{ matrix.environment }}) - Part ${i + 1}
            
            \`\`\`
            ${planChunks[i]}
            \`\`\`
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
          }

    - name: Upload Plan Artifact
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan-${{ matrix.environment }}
        path: terraform/environments/${{ matrix.environment }}/tfplan

  terraform-apply-dev:
    runs-on: [self-hosted, frontend]
    needs: [terraform-validate, terraform-security-scan]
    if: (github.ref == 'refs/heads/dev' && github.event_name == 'push') || (github.event_name == 'workflow_dispatch' && inputs.environment == 'dev' && inputs.action == 'apply')
    environment: development
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: |
        cd terraform/environments/dev
        terraform init

    - name: Terraform Apply
      run: |
        cd terraform/environments/dev
        terraform apply -auto-approve

    - name: Verify State Storage
      run: |
        cd terraform/environments/dev
        echo "✅ State stored in S3:"
        terraform state list | head -5
        echo "Total resources: $(terraform state list | wc -l)"

    - name: Create State Backup
      run: |
        cd terraform/environments/dev
        terraform state pull > terraform.tfstate.backup
        aws s3 cp terraform.tfstate.backup s3://$(terraform output -raw s3_bucket_name 2>/dev/null || echo "backup-bucket")/backups/dev/terraform.tfstate.$(date +%Y%m%d-%H%M%S)

    - name: Upload state backup artifact
      uses: actions/upload-artifact@v4
      with:
        name: terraform-state-dev-${{ github.sha }}
        path: terraform/environments/dev/terraform.tfstate.backup

  terraform-apply-staging:
    runs-on: [self-hosted, frontend]
    needs: [terraform-validate, terraform-security-scan]
    if: (github.ref == 'refs/heads/staging' && github.event_name == 'push') || (github.event_name == 'workflow_dispatch' && inputs.environment == 'staging' && inputs.action == 'apply')
    environment: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: |
        cd terraform/environments/staging
        terraform init

    - name: Terraform Plan
      run: |
        cd terraform/environments/staging
        terraform plan -out=tfplan

    - name: Terraform Apply
      run: |
        cd terraform/environments/staging
        terraform apply tfplan

    - name: Verify State Storage
      run: |
        cd terraform/environments/staging
        echo "✅ State stored in S3:"
        terraform state list | head -5
        echo "Total resources: $(terraform state list | wc -l)"

    - name: Create State Backup
      run: |
        cd terraform/environments/staging
        terraform state pull > terraform.tfstate.backup
        aws s3 cp terraform.tfstate.backup s3://$(terraform output -raw s3_bucket_name 2>/dev/null || echo "backup-bucket")/backups/staging/terraform.tfstate.$(date +%Y%m%d-%H%M%S)

    - name: Upload state backup artifact
      uses: actions/upload-artifact@v4
      with:
        name: terraform-state-staging-${{ github.sha }}
        path: terraform/environments/staging/terraform.tfstate.backup

  terraform-apply-prod:
    runs-on: [self-hosted, frontend]
    needs: [terraform-validate, terraform-security-scan]
    if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || (github.event_name == 'workflow_dispatch' && inputs.environment == 'prod' && inputs.action == 'apply')
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: |
        cd terraform/environments/prod
        terraform init

    - name: Terraform Plan
      run: |
        cd terraform/environments/prod
        terraform plan -out=tfplan

    - name: Terraform Apply
      run: |
        cd terraform/environments/prod
        terraform apply tfplan

    - name: Verify State Storage
      run: |
        cd terraform/environments/prod
        echo "✅ State stored in S3:"
        terraform state list | head -5
        echo "Total resources: $(terraform state list | wc -l)"

    - name: Create State Backup
      run: |
        cd terraform/environments/prod
        terraform state pull > terraform.tfstate.backup
        aws s3 cp terraform.tfstate.backup s3://$(terraform output -raw s3_bucket_name 2>/dev/null || echo "backup-bucket")/backups/prod/terraform.tfstate.$(date +%Y%m%d-%H%M%S)

    - name: Upload state backup artifact
      uses: actions/upload-artifact@v4
      with:
        name: terraform-state-prod-${{ github.sha }}
        path: terraform/environments/prod/terraform.tfstate.backup

    - name: Post-deployment validation
      run: |
        # Validate infrastructure health
        echo "Running post-deployment validation..."
        # Add specific health checks for your infrastructure

  notify:
    runs-on: [self-hosted, frontend]
    needs: [terraform-apply-dev, terraform-apply-staging, terraform-apply-prod]
    if: always()
    
    steps:
    - name: Determine Environment
      id: env
      run: |
        if [[ "${{ needs.terraform-apply-dev.result }}" != "skipped" ]]; then
          echo "environment=dev" >> $GITHUB_OUTPUT
        elif [[ "${{ needs.terraform-apply-staging.result }}" != "skipped" ]]; then
          echo "environment=staging" >> $GITHUB_OUTPUT
        elif [[ "${{ needs.terraform-apply-prod.result }}" != "skipped" ]]; then
          echo "environment=prod" >> $GITHUB_OUTPUT
        else
          echo "environment=unknown" >> $GITHUB_OUTPUT
        fi

    - name: Slack Notification
      uses: 8398a7/action-slack@v3
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        status: custom
        custom_payload: |
          {
            "text": "Infrastructure Deployment ${{ contains(needs.*.result, 'failure') && 'Failed ❌' || 'Completed ✅' }}",
            "attachments": [{
              "color": "${{ contains(needs.*.result, 'failure') && 'danger' || 'good' }}",
              "fields": [{
                "title": "Repository",
                "value": "${{ github.repository }}",
                "short": true
              }, {
                "title": "Environment",
                "value": "${{ steps.env.outputs.environment }}",
                "short": true
              }, {
                "title": "Terraform Version",
                "value": "${{ env.TF_VERSION }}",
                "short": true
              }, {
                "title": "AWS Region",
                "value": "${{ env.AWS_REGION }}",
                "short": true
              }, {
                "title": "Triggered By",
                "value": "${{ github.actor }}",
                "short": true
              }, {
                "title": "Branch",
                "value": "${{ github.ref_name }}",
                "short": true
              }]
            }]
          }